---
name: geode-cluster

releases:
- name: geode-bosh
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: "latest"

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 60000
  update_watch_time: 60000

instance_groups:
- name: locator
  instances: 2
  azs: [z1, z2, z3]
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: locator
    release: geode-bosh
    provides:
      locator: { as: locator }
- name: server
  instances: 4
  azs: [z1, z2, z3]
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: server
    release: geode-bosh
    provides:
      server: { as: server }
    consumes:
      locator: { from: locator }
- name: smoke-tests
  instances: 1
  azs: [z1,z2,z3]
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: smoke-tests
    release: geode-bosh
    consumes:
      server: { from: server }
      locator: { from: locator }
